name: Fusion Sync

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  trigger-deploys:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify deployment
        if: env.NETLIFY_BUILD_HOOK != ''
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          curl -X POST -d {} "$NETLIFY_BUILD_HOOK"
          echo "✓ Netlify deployment triggered"

      - name: Trigger Vercel deployment
        if: env.VERCEL_DEPLOY_HOOK != ''
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          curl -X POST -d {} "$VERCEL_DEPLOY_HOOK"
          echo "✓ Vercel deployment triggered"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const deployments = [];
            if (process.env.NETLIFY_BUILD_HOOK) deployments.push('Netlify');
            if (process.env.VERCEL_DEPLOY_HOOK) deployments.push('Vercel');
            
            const message = deployments.length > 0
              ? `✓ Deployment hooks triggered: ${deployments.join(', ')}`
              : '⚠ No deployment hooks configured';
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            })
